2023-05-26 14:00:46,715 ERROR: Exception on /remove_transl [POST] [in D:\_projects\church\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\_projects\church\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\_projects\church\app\routes.py", line 362, in remove_transl
    cursong.translated.delete(selsong)
  File "D:\_projects\church\lib\site-packages\sqlalchemy\orm\query.py", line 3165, in delete
    bulk_del = BulkDelete(self)
  File "D:\_projects\church\lib\site-packages\sqlalchemy\orm\query.py", line 3359, in __init__
    self._validate_query_state()
  File "D:\_projects\church\lib\site-packages\sqlalchemy\orm\query.py", line 3383, in _validate_query_state
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Can't call Query.update() or Query.delete() when join(), outerjoin(), select_from(), or from_self() has been called
2023-05-26 14:01:47,158 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
2023-05-26 14:14:21,344 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
2023-05-26 15:18:24,152 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
