2023-05-25 16:39:31,182 ERROR: Exception on /tag_songlist [GET] [in D:\_projects\church\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\_projects\church\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\_projects\church\app\routes.py", line 219, in tag_songlist
    return render_template('tag_songlist.html', tag=tag, songs=songs.items,
  File "D:\_projects\church\lib\site-packages\flask\templating.py", line 151, in render_template
    return _render(app, template, context)
  File "D:\_projects\church\lib\site-packages\flask\templating.py", line 132, in _render
    rv = template.render(context)
  File "D:\_projects\church\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "D:\_projects\church\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\_projects\church\app\templates\tag_songlist.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\_projects\church\app\templates\base.html", line 52, in top-level template code
    {% block content %}
  File "D:\_projects\church\app\templates\base.html", line 63, in block 'content'
    {% block app_content %}{% endblock %}
  File "D:\_projects\church\app\templates\tag_songlist.html", line 20, in block 'app_content'
    <td>{{ song.id }}</td>
  File "D:\_projects\church\lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'song' is undefined
2023-05-25 16:42:17,559 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
2023-05-26 07:10:59,190 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
2023-05-26 08:04:43,402 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
2023-05-26 08:05:35,950 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
2023-05-26 08:06:17,522 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
2023-05-26 08:08:55,190 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
2023-05-26 08:28:02,282 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
2023-05-26 09:23:05,813 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
2023-05-26 09:25:54,476 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
2023-05-26 09:33:01,334 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
2023-05-26 10:02:12,167 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
2023-05-26 10:02:20,885 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
2023-05-26 11:10:45,365 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
2023-05-26 11:10:49,811 ERROR: Exception on /view_song [GET] [in D:\_projects\church\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\_projects\church\app\routes.py", line 356, in view_song
    other_songs = Song.query.filter_by(Song.language!=song.language).all()
TypeError: Query.filter_by() takes 1 positional argument but 2 were given
2023-05-26 11:10:52,864 ERROR: Exception on /view_song [GET] [in D:\_projects\church\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\_projects\church\app\routes.py", line 356, in view_song
    other_songs = Song.query.filter_by(Song.language!=song.language).all()
TypeError: Query.filter_by() takes 1 positional argument but 2 were given
2023-05-26 11:11:57,098 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
2023-05-26 11:22:36,084 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
2023-05-26 13:02:08,551 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
2023-05-26 13:17:02,898 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
2023-05-26 13:18:41,845 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
2023-05-26 13:18:58,312 ERROR: Exception on /add_transl [GET] [in D:\_projects\church\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\_projects\church\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
TypeError: add_transl() missing 1 required positional argument: 'username'
2023-05-26 13:20:08,612 ERROR: Exception on /add_transl [GET] [in D:\_projects\church\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\_projects\church\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
TypeError: add_transl() missing 1 required positional argument: 'username'
2023-05-26 13:22:04,564 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
2023-05-26 13:22:14,600 ERROR: Exception on /add_transl [POST] [in D:\_projects\church\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\_projects\church\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\_projects\church\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\_projects\church\app\routes.py", line 325, in add_transl
    if transl_form.validate_on_submit():
  File "D:\_projects\church\lib\site-packages\flask_wtf\form.py", line 86, in validate_on_submit
    return self.is_submitted() and self.validate(extra_validators=extra_validators)
  File "D:\_projects\church\lib\site-packages\wtforms\form.py", line 329, in validate
    return super().validate(extra)
  File "D:\_projects\church\lib\site-packages\wtforms\form.py", line 146, in validate
    if not field.validate(self, extra):
  File "D:\_projects\church\lib\site-packages\wtforms\fields\core.py", line 231, in validate
    self.pre_validate(form)
  File "D:\_projects\church\lib\site-packages\wtforms\fields\choices.py", line 136, in pre_validate
    raise TypeError(self.gettext("Choices cannot be None."))
TypeError: Choices cannot be None.
2023-05-26 13:36:18,904 INFO: Church startup [in D:\_projects\church\app\__init__.py:54]
